Print autotest output to rpt
TMF3/TMF pull request #432
Opened 2021-11-24 20:39 UTC by Drofseh

I'm having an isse where the error message from a loadout check gets cut off by the dialog edge, so I can't actually see what the full problem is to fix it.

![9b762658cfa202cf566ddc00832e9dd7](https://user-images.githubusercontent.com/15274778/143309740-903421cc-6ca1-4cc5-9d29-1f58836f42bf.png)

This will just print each message to RPT, making it much easier for mission makers to debug longer errors.

Alternatives:
1. Make the dialog box wider, there is lots of room on either side to expand it
1. Allow error messages to be copied and pasted
1. Add a button that dumps errors to rpt when clicked, instead of all the time like in this PR.

2021-11-27 15:51 UTC, Freddo3000 requested changes

2021-11-27 15:51 UTC, Freddo3000 commented on addons/autotest/functions/fnc_autotest.sqf
> +        if (_output isNotEqualTo []) then {
I'd probably wrap it with [`INFO()`](https://github.com/CBATeam/CBA_A3/blob/1f780aee7f291e7598e0855bc8ba38b1df5b0d67/addons/main/script_macros_common.hpp#L225) to indicate the start and end of output. You could also add a CBA setting to toggle RPT output.

2021-12-05 10:57 UTC, Freddo3000 approved these changes

2021-12-19 17:47 UTC, headswe approved these changes

2021-12-19 17:47 UTC, merged